# Generated by Django 4.0.2 on 2022-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='brandbanner_imgs/'),
        ),
    ]
