# Generated by Django 4.0.2 on 2022-04-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_banner_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '11. Wishlists'},
        ),
    ]
