# Generated by Django 4.0.2 on 2022-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'Order In Processing'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered')], default='process', max_length=150),
        ),
    ]
