# Generated by Django 4.0.2 on 2022-04-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
