# Generated by Django 4.0.2 on 2022-04-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_banner_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'ProductAttributes'},
        ),
    ]
