# Generated by Django 4.0.2 on 2022-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_productattribute_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'Order Processed'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered')], default='process', max_length=150),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
